name: Telegram reminder
on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python3 reminder.py