name: Telegram reminder
on:
  schedule:
    - cron: '0 */4,8-20 * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run Python script with env vars
        run: |
          export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          export CHAT_ID=${{ secrets.CHAT_ID }}
          python3 reminder.py